### ISSUE TITLE
sentence segmentation bug?

### ISSUE THREAD

**Issue by Gldkslfmsd** [Gldkslfmsd/concordance-crawler#14]
-- vsimol som si, ze niektore "vety" nie su vety, ale cele texty, i ked je tam napriklad otaznik, podla ktoreho by sa ta segmentacia mala chytat

u a.json

**Comment by VincTheSecond** [comment]
In the final sentences, there are chars like `\t`, `\r`, `\n`... They definitely should not be there.

File: fly_maxpocetvet31206.json
Sentence: 7, 50

**Comment by Gldkslfmsd** [comment]
OK. fly_maxpocetvet\* is not from the very last version. Please look at "hear" and "look" firstly, they're up-to-date.

But you're right, they are some \r.

**Comment by VincTheSecond** [comment]
File: look.json
Sentence: 137

**Comment by Gldkslfmsd** [comment]
\t, \r, \n etc. fixed

**Comment by Gldkslfmsd** [comment]
there are cca 8% of potentially bad segmented sentences. 

I will separate words like `wordA.wordB` if they're not url and if both `wordA` and `wordB` are English words (presented in some nltk English dictionary or some other)

**Comment by Gldkslfmsd** [comment]
implemented
