### ISSUE TITLE
Strange encoding in JSON files

### ISSUE THREAD

**Issue by VincTheSecond** [Gldkslfmsd/concordance-crawler#15]
Some sentences contain invalid characters:

`... throughout World War II, the Kurf\u00fcrst provides an exhilarating ...`

File: fly_maxpocetvet31206.json
Sentence: 2

**Comment by VincTheSecond** [comment]
In the latest samples, there are strange unicode characters as well :-(

File: look.json
Sentence: 20

**Comment by Gldkslfmsd** [comment]
should be fixed
