### ISSUE TITLE
URLs in the sentences

### ISSUE THREAD

**Issue by VincTheSecond** [Gldkslfmsd/concordance-crawler#16]
Some sentences contain URL links:

`... positioned the [url=http://www.filsfils.com/]http://www.filsfils.com/[/url] ...`

File: fly_maxpocetvet31206.json
Sentence: 7

**Comment by Gldkslfmsd** [comment]
yes, but it's normal. It's a part of visible text on a page, probably handwritten by human, so it should remain among concordances.

Furthermore this is very rare, I have a corpus with 1173 occurrences from 297897, cca 0.4%.
